spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/compass_dev
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

server:
  port: 8080